---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8020/eureka/,http://localhost:8021/eureka/,http://localhost:8022/eureka/,http://localhost:8023/eureka/

---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
  